// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcdatabase

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Device struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Uid       string
	Serial    string
}

type Message struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Payload   json.RawMessage
	DeviceUid string
}
